### ISSUE TITLE
Error: myhead = heads[0] gives IndexError: list index out of range

### ISSUE THREAD

**Issue by nruigrok** [cltl/micro-portraits#4]
About 10% of documents produce this error:

```
~/micro-portraits/env/bin/python -m microportraits /tmp/RtmpuddLVE/file386e3f8880f8.naf > /tmp/RtmpuddLVE/file386e39b89bb7.csv
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/nel/micro-portraits/microportraits/__main__.py", line 2, in <module>
    main()
  File "/home/nel/micro-portraits/microportraits/microportraits.py", line 1394, in main
    extract_microportraits(args.inputfile, sys.stdout, args.surface)
  File "/home/nel/micro-portraits/microportraits/microportraits.py", line 1367, in extract_microportraits
    sentence_level_portraits = extract_sentence_level_portraits(nafobj)
  File "/home/nel/micro-portraits/microportraits/microportraits.py", line 1161, in extract_sentence_level_portraits
    term_portrait = extract_sentence_portrait(nafobj, term)
  File "/home/nel/micro-portraits/microportraits/microportraits.py", line 1061, in extract_sentence_portrait
    get_activity_relations(nafobj, term_portrait)
  File "/home/nel/micro-portraits/microportraits/microportraits.py", line 908, in get_activity_relations
    investigate_relations(nafobj, tid, term_portrait)
  File "/home/nel/micro-portraits/microportraits/microportraits.py", line 888, in investigate_relations
    analyze_coord_relations(nafobj, head_rel[0], term_portrait)
  File "/home/nel/micro-portraits/microportraits/microportraits.py", line 832, in analyze_coord_relations
    myhead = heads[0]
IndexError: list index out of range
```

Example document: [naf.zip](https://github.com/cltl/micro-portraits/files/3156629/naf.zip)

**Comment by nruigrok** [comment]
Het probleem lijkt wel veel groter dan 1 op de 10. Ik houd 136 artikelen over van de in totaal 2835.

**Comment by antske** [comment]
Main problem fixed: error avoided by check. New specified issue created to investigate underlying cause.
