### ISSUE TITLE
  for dep in head2deps.get(head_id): TypeError: 'NoneType' object is not iterable

### ISSUE THREAD

**Issue by nruigrok** [cltl/micro-portraits#5]
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/nel/micro-portraits/microportraits/__main__.py", line 2, in <module>
    main()
  File "/home/nel/micro-portraits/microportraits/microportraits.py", line 1394, in main
    extract_microportraits(args.inputfile, sys.stdout, args.surface)
  File "/home/nel/micro-portraits/microportraits/microportraits.py", line 1367, in extract_microportraits
    sentence_level_portraits = extract_sentence_level_portraits(nafobj)
  File "/home/nel/micro-portraits/microportraits/microportraits.py", line 1161, in extract_sentence_level_portraits
    term_portrait = extract_sentence_portrait(nafobj, term)
  File "/home/nel/micro-portraits/microportraits/microportraits.py", line 1048, in extract_sentence_portrait
    add_rows_for_description(dep[0],nafobj,head2deps,term_portrait,'property')
  File "/home/nel/micro-portraits/microportraits/microportraits.py", line 1014, in add_rows_for_description
    for dep in head2deps.get(head_id):
TypeError: 'NoneType' object is not iterable

**Comment by nruigrok** [comment]
now with attachment
[naf.zip](https://github.com/cltl/micro-portraits/files/3161851/naf.zip)

**Comment by antske** [comment]
Fixed: in correct parsers, all coordinators have dependents, but not all parsers are correct. Code now skips step of collecting daughters for coordinators without dependents.
